spring:
  application:
    name: JSC-Test

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

# loại bỏ do deploy (render) ko dùng được
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_NAME}
#    password: ${EMAIL_PASS}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connection timeout: 10000
#          timeout: 10000
#          write timeout: 10000

  quartz:
    auto-startup: true

# SendGrid
sendgrid:
  api:
    key: ${SEND_GRID_API_KEY}
  from:
    email: ${SEND_GRID_FROM_EMAIL}
    name: ${SEND_GRID_FROM_NAME}